namespace Service2TheRescue.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class NewMigrate6 : DbMigration
    {
        public override void Up()
        {
            DropColumn("dbo.UserInfos", "Name");
            DropColumn("dbo.UserInfos", "Division");
            DropColumn("dbo.UserInfos", "Latitude");
            DropColumn("dbo.UserInfos", "Longitude");
            DropColumn("dbo.UserInfos", "EmailPreferencesAutoBcc");
            DropColumn("dbo.UserInfos", "EmailPreferencesAutoBccStayInTouch");
            DropColumn("dbo.UserInfos", "EmailPreferencesStayInTouchReminder");
            DropColumn("dbo.UserInfos", "SenderEmail");
            DropColumn("dbo.UserInfos", "SenderName");
            DropColumn("dbo.UserInfos", "Signature");
            DropColumn("dbo.UserInfos", "StayInTouchSubject");
            DropColumn("dbo.UserInfos", "StayInTouchSignature");
            DropColumn("dbo.UserInfos", "StayInTouchNote");
            DropColumn("dbo.UserInfos", "Phone");
            DropColumn("dbo.UserInfos", "Fax");
            DropColumn("dbo.UserInfos", "Alias");
            DropColumn("dbo.UserInfos", "CommunityNickname");
            DropColumn("dbo.UserInfos", "IsBadged");
            DropColumn("dbo.UserInfos", "BadgeText");
            DropColumn("dbo.UserInfos", "TimeZoneSidKey");
            DropColumn("dbo.UserInfos", "LocaleSidKey");
            DropColumn("dbo.UserInfos", "ReceivesInfoEmails");
            DropColumn("dbo.UserInfos", "ReceivesAdminInfoEmails");
            DropColumn("dbo.UserInfos", "EmailEncodingKey");
            DropColumn("dbo.UserInfos", "ProfileId");
            DropColumn("dbo.UserInfos", "UserType");
            DropColumn("dbo.UserInfos", "LanguageLocaleKey");
            DropColumn("dbo.UserInfos", "EmployeeNumber");
            DropColumn("dbo.UserInfos", "DelegatedApproverId");
            DropColumn("dbo.UserInfos", "ManagerId");
            DropColumn("dbo.UserInfos", "LastLoginDate");
            DropColumn("dbo.UserInfos", "LastPasswordChangeDate");
            DropColumn("dbo.UserInfos", "CreatedDate");
            DropColumn("dbo.UserInfos", "CreatedById");
            DropColumn("dbo.UserInfos", "LastModifiedDate");
            DropColumn("dbo.UserInfos", "LastModifiedById");
            DropColumn("dbo.UserInfos", "SystemModstamp");
            DropColumn("dbo.UserInfos", "OfflineTrialExpirationDate");
            DropColumn("dbo.UserInfos", "OfflinePdaTrialExpirationDate");
            DropColumn("dbo.UserInfos", "UserPermissionsMarketingUser");
            DropColumn("dbo.UserInfos", "UserPermissionsOfflineUser");
            DropColumn("dbo.UserInfos", "UserPermissionsCallCenterAutoLogin");
            DropColumn("dbo.UserInfos", "UserPermissionsMobileUser");
            DropColumn("dbo.UserInfos", "UserPermissionsSFContentUser");
            DropColumn("dbo.UserInfos", "UserPermissionsKnowledgeUser");
            DropColumn("dbo.UserInfos", "UserPermissionsInteractionUser");
            DropColumn("dbo.UserInfos", "UserPermissionsSupportUser");
            DropColumn("dbo.UserInfos", "UserPermissionsJigsawProspectingUser");
            DropColumn("dbo.UserInfos", "UserPermissionsSiteforceContributorUser");
            DropColumn("dbo.UserInfos", "UserPermissionsSiteforcePublisherUser");
            DropColumn("dbo.UserInfos", "UserPermissionsChatterAnswersUser");
            DropColumn("dbo.UserInfos", "UserPermissionsWorkDotComUserFeature");
            DropColumn("dbo.UserInfos", "ForecastEnabled");
            DropColumn("dbo.UserInfos", "UserPreferencesActivityRemindersPopup");
            DropColumn("dbo.UserInfos", "UserPreferencesEventRemindersCheckboxDefault");
            DropColumn("dbo.UserInfos", "UserPreferencesTaskRemindersCheckboxDefault");
            DropColumn("dbo.UserInfos", "UserPreferencesReminderSoundOff");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableAllFeedsEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableFollowersEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableProfilePostEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableChangeCommentEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableLaterCommentEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesDisProfPostCommentEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesContentNoEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesContentEmailAsAndWhen");
            DropColumn("dbo.UserInfos", "UserPreferencesApexPagesDeveloperMode");
            DropColumn("dbo.UserInfos", "UserPreferencesHideCSNGetChatterMobileTask");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableMentionsPostEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesDisMentionsCommentEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesHideCSNDesktopTask");
            DropColumn("dbo.UserInfos", "UserPreferencesHideChatterOnboardingSplash");
            DropColumn("dbo.UserInfos", "UserPreferencesHideSecondChatterOnboardingSplash");
            DropColumn("dbo.UserInfos", "UserPreferencesDisCommentAfterLikeEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableLikeEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableMessageEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesJigsawListUser");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableBookmarkEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableSharePostEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesEnableAutoSubForFeeds");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableFileShareNotificationsForApi");
            DropColumn("dbo.UserInfos", "UserPreferencesShowTitleToExternalUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowManagerToExternalUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowEmailToExternalUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowWorkPhoneToExternalUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowMobilePhoneToExternalUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowFaxToExternalUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowStreetAddressToExternalUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowCityToExternalUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowStateToExternalUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowPostalCodeToExternalUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowCountryToExternalUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowProfilePicToGuestUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowTitleToGuestUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowCityToGuestUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowStateToGuestUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowPostalCodeToGuestUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesShowCountryToGuestUsers");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableFeedbackEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableWorkEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesHideS1BrowserUI");
            DropColumn("dbo.UserInfos", "UserPreferencesDisableEndorsementEmail");
            DropColumn("dbo.UserInfos", "UserPreferencesLightningExperiencePreferred");
            DropColumn("dbo.UserInfos", "ContactId");
            DropColumn("dbo.UserInfos", "AccountId");
            DropColumn("dbo.UserInfos", "CallCenterId");
            DropColumn("dbo.UserInfos", "Extension");
            DropColumn("dbo.UserInfos", "FederationIdentifier");
            DropColumn("dbo.UserInfos", "SmallPhotoUrl");
            DropColumn("dbo.UserInfos", "DigestFrequency");
            DropColumn("dbo.UserInfos", "DefaultGroupNotificationFrequency");
            DropColumn("dbo.UserInfos", "JigsawImportLimitOverride");
            DropColumn("dbo.UserInfos", "LastViewedDate");
            DropColumn("dbo.UserInfos", "LastReferencedDate");
        }
        
        public override void Down()
        {
            AddColumn("dbo.UserInfos", "LastReferencedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.UserInfos", "LastViewedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.UserInfos", "JigsawImportLimitOverride", c => c.Int());
            AddColumn("dbo.UserInfos", "DefaultGroupNotificationFrequency", c => c.String());
            AddColumn("dbo.UserInfos", "DigestFrequency", c => c.String());
            AddColumn("dbo.UserInfos", "SmallPhotoUrl", c => c.String());
            AddColumn("dbo.UserInfos", "FederationIdentifier", c => c.String(maxLength: 512));
            AddColumn("dbo.UserInfos", "Extension", c => c.String());
            AddColumn("dbo.UserInfos", "CallCenterId", c => c.String());
            AddColumn("dbo.UserInfos", "AccountId", c => c.String());
            AddColumn("dbo.UserInfos", "ContactId", c => c.String());
            AddColumn("dbo.UserInfos", "UserPreferencesLightningExperiencePreferred", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableEndorsementEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesHideS1BrowserUI", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableWorkEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableFeedbackEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowCountryToGuestUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowPostalCodeToGuestUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowStateToGuestUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowCityToGuestUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowTitleToGuestUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowProfilePicToGuestUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowCountryToExternalUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowPostalCodeToExternalUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowStateToExternalUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowCityToExternalUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowStreetAddressToExternalUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowFaxToExternalUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowMobilePhoneToExternalUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowWorkPhoneToExternalUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowEmailToExternalUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowManagerToExternalUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesShowTitleToExternalUsers", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableFileShareNotificationsForApi", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesEnableAutoSubForFeeds", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableSharePostEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableBookmarkEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesJigsawListUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableMessageEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableLikeEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisCommentAfterLikeEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesHideSecondChatterOnboardingSplash", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesHideChatterOnboardingSplash", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesHideCSNDesktopTask", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisMentionsCommentEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableMentionsPostEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesHideCSNGetChatterMobileTask", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesApexPagesDeveloperMode", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesContentEmailAsAndWhen", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesContentNoEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisProfPostCommentEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableLaterCommentEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableChangeCommentEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableProfilePostEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableFollowersEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesDisableAllFeedsEmail", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesReminderSoundOff", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesTaskRemindersCheckboxDefault", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesEventRemindersCheckboxDefault", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPreferencesActivityRemindersPopup", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "ForecastEnabled", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsWorkDotComUserFeature", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsChatterAnswersUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsSiteforcePublisherUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsSiteforceContributorUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsJigsawProspectingUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsSupportUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsInteractionUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsKnowledgeUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsSFContentUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsMobileUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsCallCenterAutoLogin", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsOfflineUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "UserPermissionsMarketingUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "OfflinePdaTrialExpirationDate", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.UserInfos", "OfflineTrialExpirationDate", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.UserInfos", "SystemModstamp", c => c.DateTimeOffset(nullable: false, precision: 7));
            AddColumn("dbo.UserInfos", "LastModifiedById", c => c.String());
            AddColumn("dbo.UserInfos", "LastModifiedDate", c => c.DateTimeOffset(nullable: false, precision: 7));
            AddColumn("dbo.UserInfos", "CreatedById", c => c.String());
            AddColumn("dbo.UserInfos", "CreatedDate", c => c.DateTimeOffset(nullable: false, precision: 7));
            AddColumn("dbo.UserInfos", "LastPasswordChangeDate", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.UserInfos", "LastLoginDate", c => c.DateTimeOffset(precision: 7));
            AddColumn("dbo.UserInfos", "ManagerId", c => c.String());
            AddColumn("dbo.UserInfos", "DelegatedApproverId", c => c.String());
            AddColumn("dbo.UserInfos", "EmployeeNumber", c => c.String(maxLength: 20));
            AddColumn("dbo.UserInfos", "LanguageLocaleKey", c => c.String());
            AddColumn("dbo.UserInfos", "UserType", c => c.String());
            AddColumn("dbo.UserInfos", "ProfileId", c => c.String());
            AddColumn("dbo.UserInfos", "EmailEncodingKey", c => c.String());
            AddColumn("dbo.UserInfos", "ReceivesAdminInfoEmails", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "ReceivesInfoEmails", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "LocaleSidKey", c => c.String());
            AddColumn("dbo.UserInfos", "TimeZoneSidKey", c => c.String());
            AddColumn("dbo.UserInfos", "BadgeText", c => c.String(maxLength: 80));
            AddColumn("dbo.UserInfos", "IsBadged", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "CommunityNickname", c => c.String(maxLength: 40));
            AddColumn("dbo.UserInfos", "Alias", c => c.String(maxLength: 8));
            AddColumn("dbo.UserInfos", "Fax", c => c.String());
            AddColumn("dbo.UserInfos", "Phone", c => c.String());
            AddColumn("dbo.UserInfos", "StayInTouchNote", c => c.String(maxLength: 512));
            AddColumn("dbo.UserInfos", "StayInTouchSignature", c => c.String(maxLength: 512));
            AddColumn("dbo.UserInfos", "StayInTouchSubject", c => c.String(maxLength: 80));
            AddColumn("dbo.UserInfos", "Signature", c => c.String(maxLength: 1333));
            AddColumn("dbo.UserInfos", "SenderName", c => c.String(maxLength: 80));
            AddColumn("dbo.UserInfos", "SenderEmail", c => c.String());
            AddColumn("dbo.UserInfos", "EmailPreferencesStayInTouchReminder", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "EmailPreferencesAutoBccStayInTouch", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "EmailPreferencesAutoBcc", c => c.Boolean(nullable: false));
            AddColumn("dbo.UserInfos", "Longitude", c => c.Double());
            AddColumn("dbo.UserInfos", "Latitude", c => c.Double());
            AddColumn("dbo.UserInfos", "Division", c => c.String(maxLength: 80));
            AddColumn("dbo.UserInfos", "Name", c => c.String(maxLength: 121));
        }
    }
}
