namespace Service2TheRescue.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class NewMigrate5 : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "dbo.UserInfos",
                c => new
                    {
                        Id = c.String(nullable: false, maxLength: 128),
                        Username = c.String(maxLength: 80),
                        LastName = c.String(maxLength: 80),
                        FirstName = c.String(maxLength: 40),
                        Name = c.String(maxLength: 121),
                        CompanyName = c.String(maxLength: 80),
                        Division = c.String(maxLength: 80),
                        Department = c.String(maxLength: 80),
                        Title = c.String(maxLength: 80),
                        Street = c.String(),
                        City = c.String(maxLength: 40),
                        State = c.String(maxLength: 80),
                        PostalCode = c.String(maxLength: 20),
                        Country = c.String(maxLength: 80),
                        Latitude = c.Double(),
                        Longitude = c.Double(),
                        Email = c.String(),
                        EmailPreferencesAutoBcc = c.Boolean(nullable: false),
                        EmailPreferencesAutoBccStayInTouch = c.Boolean(nullable: false),
                        EmailPreferencesStayInTouchReminder = c.Boolean(nullable: false),
                        SenderEmail = c.String(),
                        SenderName = c.String(maxLength: 80),
                        Signature = c.String(maxLength: 1333),
                        StayInTouchSubject = c.String(maxLength: 80),
                        StayInTouchSignature = c.String(maxLength: 512),
                        StayInTouchNote = c.String(maxLength: 512),
                        Phone = c.String(),
                        Fax = c.String(),
                        MobilePhone = c.String(),
                        Alias = c.String(maxLength: 8),
                        CommunityNickname = c.String(maxLength: 40),
                        IsBadged = c.Boolean(nullable: false),
                        BadgeText = c.String(maxLength: 80),
                        IsActive = c.Boolean(nullable: false),
                        TimeZoneSidKey = c.String(),
                        UserRoleId = c.String(),
                        LocaleSidKey = c.String(),
                        ReceivesInfoEmails = c.Boolean(nullable: false),
                        ReceivesAdminInfoEmails = c.Boolean(nullable: false),
                        EmailEncodingKey = c.String(),
                        ProfileId = c.String(),
                        UserType = c.String(),
                        LanguageLocaleKey = c.String(),
                        EmployeeNumber = c.String(maxLength: 20),
                        DelegatedApproverId = c.String(),
                        ManagerId = c.String(),
                        LastLoginDate = c.DateTimeOffset(precision: 7),
                        LastPasswordChangeDate = c.DateTimeOffset(precision: 7),
                        CreatedDate = c.DateTimeOffset(nullable: false, precision: 7),
                        CreatedById = c.String(),
                        LastModifiedDate = c.DateTimeOffset(nullable: false, precision: 7),
                        LastModifiedById = c.String(),
                        SystemModstamp = c.DateTimeOffset(nullable: false, precision: 7),
                        OfflineTrialExpirationDate = c.DateTimeOffset(precision: 7),
                        OfflinePdaTrialExpirationDate = c.DateTimeOffset(precision: 7),
                        UserPermissionsMarketingUser = c.Boolean(nullable: false),
                        UserPermissionsOfflineUser = c.Boolean(nullable: false),
                        UserPermissionsCallCenterAutoLogin = c.Boolean(nullable: false),
                        UserPermissionsMobileUser = c.Boolean(nullable: false),
                        UserPermissionsSFContentUser = c.Boolean(nullable: false),
                        UserPermissionsKnowledgeUser = c.Boolean(nullable: false),
                        UserPermissionsInteractionUser = c.Boolean(nullable: false),
                        UserPermissionsSupportUser = c.Boolean(nullable: false),
                        UserPermissionsJigsawProspectingUser = c.Boolean(nullable: false),
                        UserPermissionsSiteforceContributorUser = c.Boolean(nullable: false),
                        UserPermissionsSiteforcePublisherUser = c.Boolean(nullable: false),
                        UserPermissionsChatterAnswersUser = c.Boolean(nullable: false),
                        UserPermissionsWorkDotComUserFeature = c.Boolean(nullable: false),
                        ForecastEnabled = c.Boolean(nullable: false),
                        UserPreferencesActivityRemindersPopup = c.Boolean(nullable: false),
                        UserPreferencesEventRemindersCheckboxDefault = c.Boolean(nullable: false),
                        UserPreferencesTaskRemindersCheckboxDefault = c.Boolean(nullable: false),
                        UserPreferencesReminderSoundOff = c.Boolean(nullable: false),
                        UserPreferencesDisableAllFeedsEmail = c.Boolean(nullable: false),
                        UserPreferencesDisableFollowersEmail = c.Boolean(nullable: false),
                        UserPreferencesDisableProfilePostEmail = c.Boolean(nullable: false),
                        UserPreferencesDisableChangeCommentEmail = c.Boolean(nullable: false),
                        UserPreferencesDisableLaterCommentEmail = c.Boolean(nullable: false),
                        UserPreferencesDisProfPostCommentEmail = c.Boolean(nullable: false),
                        UserPreferencesContentNoEmail = c.Boolean(nullable: false),
                        UserPreferencesContentEmailAsAndWhen = c.Boolean(nullable: false),
                        UserPreferencesApexPagesDeveloperMode = c.Boolean(nullable: false),
                        UserPreferencesHideCSNGetChatterMobileTask = c.Boolean(nullable: false),
                        UserPreferencesDisableMentionsPostEmail = c.Boolean(nullable: false),
                        UserPreferencesDisMentionsCommentEmail = c.Boolean(nullable: false),
                        UserPreferencesHideCSNDesktopTask = c.Boolean(nullable: false),
                        UserPreferencesHideChatterOnboardingSplash = c.Boolean(nullable: false),
                        UserPreferencesHideSecondChatterOnboardingSplash = c.Boolean(nullable: false),
                        UserPreferencesDisCommentAfterLikeEmail = c.Boolean(nullable: false),
                        UserPreferencesDisableLikeEmail = c.Boolean(nullable: false),
                        UserPreferencesDisableMessageEmail = c.Boolean(nullable: false),
                        UserPreferencesJigsawListUser = c.Boolean(nullable: false),
                        UserPreferencesDisableBookmarkEmail = c.Boolean(nullable: false),
                        UserPreferencesDisableSharePostEmail = c.Boolean(nullable: false),
                        UserPreferencesEnableAutoSubForFeeds = c.Boolean(nullable: false),
                        UserPreferencesDisableFileShareNotificationsForApi = c.Boolean(nullable: false),
                        UserPreferencesShowTitleToExternalUsers = c.Boolean(nullable: false),
                        UserPreferencesShowManagerToExternalUsers = c.Boolean(nullable: false),
                        UserPreferencesShowEmailToExternalUsers = c.Boolean(nullable: false),
                        UserPreferencesShowWorkPhoneToExternalUsers = c.Boolean(nullable: false),
                        UserPreferencesShowMobilePhoneToExternalUsers = c.Boolean(nullable: false),
                        UserPreferencesShowFaxToExternalUsers = c.Boolean(nullable: false),
                        UserPreferencesShowStreetAddressToExternalUsers = c.Boolean(nullable: false),
                        UserPreferencesShowCityToExternalUsers = c.Boolean(nullable: false),
                        UserPreferencesShowStateToExternalUsers = c.Boolean(nullable: false),
                        UserPreferencesShowPostalCodeToExternalUsers = c.Boolean(nullable: false),
                        UserPreferencesShowCountryToExternalUsers = c.Boolean(nullable: false),
                        UserPreferencesShowProfilePicToGuestUsers = c.Boolean(nullable: false),
                        UserPreferencesShowTitleToGuestUsers = c.Boolean(nullable: false),
                        UserPreferencesShowCityToGuestUsers = c.Boolean(nullable: false),
                        UserPreferencesShowStateToGuestUsers = c.Boolean(nullable: false),
                        UserPreferencesShowPostalCodeToGuestUsers = c.Boolean(nullable: false),
                        UserPreferencesShowCountryToGuestUsers = c.Boolean(nullable: false),
                        UserPreferencesDisableFeedbackEmail = c.Boolean(nullable: false),
                        UserPreferencesDisableWorkEmail = c.Boolean(nullable: false),
                        UserPreferencesHideS1BrowserUI = c.Boolean(nullable: false),
                        UserPreferencesDisableEndorsementEmail = c.Boolean(nullable: false),
                        UserPreferencesLightningExperiencePreferred = c.Boolean(nullable: false),
                        ContactId = c.String(),
                        AccountId = c.String(),
                        CallCenterId = c.String(),
                        Extension = c.String(),
                        FederationIdentifier = c.String(maxLength: 512),
                        AboutMe = c.String(),
                        FullPhotoUrl = c.String(),
                        SmallPhotoUrl = c.String(),
                        DigestFrequency = c.String(),
                        DefaultGroupNotificationFrequency = c.String(),
                        JigsawImportLimitOverride = c.Int(),
                        LastViewedDate = c.DateTimeOffset(precision: 7),
                        LastReferencedDate = c.DateTimeOffset(precision: 7),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("dbo.UserInfos");
        }
    }
}
